train:
  epoch: 1000
  snapshot_interval: 2000
  batchsize: 64
  validsize: 64
  z_dim: 128

dataset:
  extension: ".png"
  train_size: 128

model:
  generator:
    z_dim: 128
    sn: true
    lr: 0.0002
    b1: 0.5
    b2: 0.99
    mode: "train"
  discriminator:
    sn: true
    lr: 0.0002
    b1: 0.5
    b2: 0.99
    mode: "train"

loss:
  adv:
    w: 1.0
    type: "hinge"
  gp:
    w: 10.0
    center: "zero"
    type: "dragan"